export interface CovidEntity {
    /** If `true`, it means this data was generated by us and is not from the API. */
    readonly isPseudo: boolean;

    readonly country: string;
    readonly province: string;
    readonly updatedAt: Date;
    readonly stats: {
        readonly confirmed: number;
        readonly deaths: number;
        readonly recovered: number;
    };
    readonly coordinates: {
        readonly latitude: number;
        readonly longitude: number;
    };
    readonly isCountry: boolean;
    readonly displayName: string;

    /** This will be unique among all entities, whether it be a country or a province. */
    readonly _uid: string;
}
